### ISSUE TITLE
Surface dependency info in the dependent executable

### ISSUE THREAD

**Issue by nastevens** [Shnatsel/rust-audit#2]
Right now rust-audit requires running a separate executable to get the `Cargo.lock` information. It'd be really useful to surface the `Cargo.lock` information to the running program itself - even as just a `&'static str` so that it can be reported dynamically.

I am specifically thinking about some production code I own that returns build info through a `/buildinfo` HTTP GET endpoint. It'd be awesome if I could return the whole `Cargo.lock` through something like `/buildinfo/dependencies`

**Comment by Shnatsel** [comment]
It is currently encoded as `&'static str` and should be (in theory) accessible to the host program: https://github.com/Shnatsel/rust-audit/blob/master/auditable/src/lib.rs#L4

So I guess all you need to add to `auditable` crate is a function that returns a reference to that string. That sounds like a 3-line change, I'd welcome a pull request.

**Comment by Shnatsel** [comment]
Implemented in a9b8a073f2fb5b4cb4f10c75ab938a42a2c781a1#diff-fc4b1902e6af6362b980fc4370de0a32

**Comment by Shnatsel** [comment]
Reopening because I'm transitioning to a compressed format and it doesn't make sense to expose the gzipped data.

However, third-party solutions to this exist: https://github.com/danielschemmel/build-info https://github.com/lukaslueg/built

This will also be easy to implement if we have Cargo cooperation, something like `include_str!(env!("CARGO_DEPENDENCY_FILE"));`

**Comment by Shnatsel** [comment]
`auditable::inject_dependency_list!()` now returns the compressed dependency list as `&[u8]`, but you'd have to decompress it (zlib format) to get to the actual string, so it's not massively useful.
